-- Catálogo real de MAS. Generado desde Supabase (29 productos).
-- Idempotente: inserta o actualiza por sku. No borra filas extra.
-- La existencia (quantity) solo se carga en SKU nuevos; no pisa stock ya existente.
-- Las series de equipos viven en public.serial_numbers (no forman parte de este seed).
-- Regenerar: bash scripts/export-catalog.sh

begin;
alter table public.inventory_items disable trigger inventory_items_protect_quantity;

insert into public.inventory_items (
  sku,
  name,
  category,
  item_kind,
  description,
  quantity,
  min_stock,
  unit,
  location,
  brand,
  model,
  serial_number,
  unit_price,
  supplier,
  expiry_date,
  manufactured_at,
  notes,
  asset_status,
  last_maintenance_date,
  next_maintenance_date,
  is_active,
  tracks_lot,
  tracks_serial,
  tracks_expiry,
  max_stock,
  reorder_point,
  part_number,
  manufacturer,
  subcategory
) values
  ('ACCESORIOS-000001', 'Expiración calve, patientsys', 'accesorios', 'producto', 'Válvula respiratoria ', 22, 0, 'pieza', 'A/1', 'Drager ', '', 'N/A', 0.0, 'Drager', NULL, NULL, '', 'operativo', NULL, NULL, true, true, false, false, 0, 0, '8410580', 'Drager', ''),
  ('ACCESORIOS-000002', 'Adaptador de aquecedor de tubo', 'accesorios', 'producto', '', 126, 0, 'pieza', 'A/1', 'Drager', 'Drager ', '', 46.0, 'Drager', NULL, NULL, '', 'operativo', NULL, NULL, true, true, false, false, 0, 0, '8414968', 'Drager', ''),
  ('ACCESORIOS-000003', 'Probe 3, skin temp, reusable', 'accesorios', 'producto', '', 46, 0, 'pieza', 'A/2', 'Drager', 'Drager', '2152-01', 0.0, 'Drager', NULL, NULL, '', 'operativo', NULL, NULL, true, true, false, false, 0, 0, 'MU11225', 'Drager', ''),
  ('ACCESORIOS-000004', 'Probe skin 3, skin temp, reusable', 'accesorios', 'producto', '', 2, 0, 'pieza', 'A/2', 'Drager', 'Drager', '2145-02', 0.0, 'Drager', NULL, NULL, '', 'operativo', NULL, NULL, true, true, false, false, 0, 0, 'MU11225', 'Drager', ''),
  ('ACCESORIOS-000005', 'Probé 3, skin temp, reusable', 'accesorios', 'producto', '', 3, 0, 'pieza', 'A/2', 'Drager', '', '2217-01', 0.0, 'Drager', NULL, NULL, '', 'operativo', NULL, NULL, true, true, false, false, 0, 0, '2217-01', 'Drager', ''),
  ('ACCESORIOS-000006', 'Temperature probe skin 3m', 'accesorios', 'producto', '', 1, 0, 'pieza', 'A/2', 'Drager', '', '', 0.0, 'Drager ', NULL, NULL, '', 'operativo', NULL, NULL, true, true, false, false, 0, 0, '', 'Drager', ''),
  ('EQUIPO-000001', 'IntelliVue Patient Monitor MX550', 'equipos', 'equipo', '', 21, 0, 'pieza', 'Sala de cámaras', 'Philips', 'MX550', '', 0.0, 'Philips', NULL, NULL, '', 'operativo', NULL, NULL, true, false, true, false, 0, 0, '866066', 'Philips', ''),
  ('EQUIPO-000002', 'Monitor fetal Avalon FM20/FM30', 'equipos', 'equipo', '', 20, 0, 'pieza', 'Sala de cámaras', 'Philips', 'FM20/FM30', '', 0.0, 'Philips', NULL, NULL, '', 'operativo', NULL, NULL, true, false, true, false, 0, 0, 'M2702A', 'Philips', ''),
  ('EQUIPO-000003', 'D-Vapor', 'equipos', 'equipo', '', 1, 0, 'pieza', 'Sala de cámaras', 'Drager', 'D-Vapor', '', 0.0, 'Drager', NULL, NULL, '', 'operativo', NULL, NULL, true, false, true, false, 0, 0, 'M35500', 'Drager', ''),
  ('EQUIPO-000004', 'Monitor de signos vitales Vista 120 C', 'equipos', 'equipo', '', 4, 0, 'pieza', 'Sala de cámaras', 'Drager', 'Vista 120 C', '', 0.0, 'Drager', NULL, NULL, '', 'operativo', NULL, NULL, true, false, true, false, 0, 0, 'MS34009', 'Drager', ''),
  ('EQUIPO-000005', 'Mounting arm with basket', 'equipos', 'equipo', '', 1, 0, 'pieza', 'Sala de cámaras', 'Drager', '', '', 0.0, 'Drager', NULL, NULL, '', 'operativo', NULL, NULL, true, false, true, false, 0, 0, '2601148', 'Drager', ''),
  ('EQUIPO-000006', 'Desfibrilador EFFICIA DFM100', 'equipos', 'equipo', '', 3, 0, 'pieza', 'Sala de cámaras', 'Philips', 'EFFICIA DFM100', '', 0.0, 'Philips', NULL, NULL, '', 'operativo', NULL, NULL, true, false, true, false, 0, 0, '866199', 'Philips', ''),
  ('INSUMOS-000001', 'Mask silicone inf small 0 reusable', 'insumos', 'producto', '', 14, 0, 'pieza', 'A/2', 'Drager', '', '', 0.0, 'Drager', NULL, NULL, '', 'operativo', NULL, NULL, true, true, false, true, 0, 0, 'MP01910', 'Drager', ''),
  ('INSUMOS-000002', 'Tyvek Roll with STERRAD Chemical Indicator', 'insumos', 'producto', '', 12, 0, 'caja', 'Insumos', 'ASP', '', '', 0.0, 'ASP', NULL, NULL, '', 'operativo', NULL, NULL, true, true, false, true, 0, 0, '12435', 'ASP', ''),
  ('INSUMOS-000003', 'Biological Indicators/Process Challenge Devices', 'insumos', 'producto', '', 25, 0, 'caja', '', 'ASP', '', '', 0.0, 'ASP', '2025-01-29', NULL, '', 'operativo', NULL, NULL, true, true, false, true, 0, 0, '43210-30', '', ''),
  ('INSUMOS-000004', 'Tyvek Heat Seal Pouch with STERRAD Chemical Indicator', 'insumos', 'producto', '', 5, 0, 'caja', 'Insumos', 'ASP', '', '', 0.0, 'ASP', '2026-09-17', '2024-09-17', '', 'operativo', NULL, NULL, true, true, false, true, 0, 0, '12532', 'ASP', ''),
  ('INSUMOS-000005', 'STERRAD 100NX Cassette', 'insumos', 'producto', '', 71, 0, 'pieza', '', 'ASP', '', '', 0.0, 'ASP', '2026-12-03', NULL, '', 'operativo', NULL, NULL, true, true, false, true, 0, 0, '10144', '', ''),
  ('INSUMOS-000006', 'STERRAD Chemical Indicator Strip', 'insumos', 'producto', '', 4, 0, 'pieza', 'Insumos', 'ASP', '', '', 0.0, 'ASP', '2026-05-18', '2024-11-18', '', 'operativo', NULL, NULL, true, true, false, true, 0, 0, '14100', 'ASP', ''),
  ('INSUMOS-000007', 'STERRAD SEALSURE Chemical Indicator Tape', 'insumos', 'producto', '', 2, 0, 'pieza', '', 'ASP', '', '', 0.0, 'ASP', '2027-03-02', '2025-05-02', '', 'operativo', NULL, NULL, true, true, false, true, 0, 0, '14202NL', 'ASP', ''),
  ('INSUMOS-000008', 'Tyvek Heat Seal Pouch with STERRAD Chemical Indicator', 'insumos', 'producto', '', 8, 0, 'pieza', '', 'ASP', '', '', 0.0, 'ASP', '2025-03-01', '2026-12-19', '', 'operativo', NULL, NULL, true, true, false, true, 0, 0, '12541', 'Asp', ''),
  ('INSUMOS-000009', 'STERRAD 100NX Cassette Collector Box', 'insumos', 'producto', '', 5, 0, 'pieza', '', 'ASP', '', '', 0.0, 'ASP', '2057-10-05', '2023-03-01', '', 'operativo', NULL, NULL, true, true, false, true, 0, 0, '20227', 'ASP', ''),
  ('INSUMOS-000010', 'Sterilization Wrap', 'insumos', 'producto', '', 28, 0, 'pieza', '', 'Halyard', '', '', 0.0, 'ASP', '2051-10-05', '2025-05-02', '', 'operativo', NULL, NULL, true, true, false, true, 0, 0, '68040', 'Halyard', ''),
  ('INSUMOS-000011', 'Tyvek Roll with STERRAD Chemical Indicator', 'insumos', 'producto', '', 5, 0, 'pieza', '', 'ASP', '', '', 0.0, 'ASP', '2026-02-20', NULL, '', 'operativo', NULL, NULL, true, true, false, true, 0, 0, '12415', 'ASP', ''),
  ('INSUMOS-000012', 'Tyvek Roll with STERRAD Chemical Indicator', 'insumos', 'producto', '', 4, 0, 'pieza', '', 'ASP', '', '', 0.0, 'ASP', '2026-11-04', NULL, '', 'operativo', NULL, NULL, true, true, false, true, 0, 0, '12425', 'ASP', ''),
  ('INSUMOS-000013', 'Tyvek Roll with STERRAD Chemical Indicator', 'insumos', 'producto', '', 5, 0, 'pieza', '', 'ASP', '', '', 0.0, 'ASP', '2027-09-04', NULL, '', 'operativo', NULL, NULL, true, true, false, true, 0, 0, '12420', 'ASP', ''),
  ('INSUMOS-000014', 'Tyvek Roll with STERRAD Chemical Indicator', 'insumos', 'producto', '', 1, 0, 'pieza', '', 'ASP', '', '', 0.0, 'ASP', '2027-07-28', NULL, '', 'operativo', NULL, NULL, true, true, false, true, 0, 0, '12410', 'ASP', ''),
  ('INSUMOS-000015', 'VERISURE Boeing-Dick Test Pack', 'insumos', 'producto', '', 2, 0, 'caja', '', 'ASP', '', '', 0.0, 'ASP', '2028-09-01', '2023-09-01', '', 'operativo', NULL, NULL, true, true, false, true, 0, 0, '73180', 'ASP', ''),
  ('INSUMOS-000016', 'Process Challenge Device (PCD)', 'insumos', 'producto', '', 2, 0, 'caja', '', 'ASP', '', '', 0.0, 'ASP', '2028-09-01', NULL, '', 'operativo', NULL, NULL, true, true, false, true, 0, 0, '73160', 'ASP', ''),
  ('REFACCIONES-000001', 'Superficie de prevención NP50', 'refacciones', 'producto', '', 0, 10, 'pieza', 'Palma ', 'Hill-Rom', 'NP50', '2540-N-0096-03', 5500.0, 'Hill-Rom', NULL, NULL, '', 'operativo', NULL, NULL, true, false, true, false, 0, 10, 'ASS028', 'Hill-Rom', '')
on conflict (sku) do update set
  name = excluded.name,
  category = excluded.category,
  item_kind = excluded.item_kind,
  description = excluded.description,
  min_stock = excluded.min_stock,
  unit = excluded.unit,
  location = excluded.location,
  brand = excluded.brand,
  model = excluded.model,
  serial_number = excluded.serial_number,
  unit_price = excluded.unit_price,
  supplier = excluded.supplier,
  expiry_date = excluded.expiry_date,
  manufactured_at = excluded.manufactured_at,
  notes = excluded.notes,
  asset_status = excluded.asset_status,
  last_maintenance_date = excluded.last_maintenance_date,
  next_maintenance_date = excluded.next_maintenance_date,
  is_active = excluded.is_active,
  tracks_lot = excluded.tracks_lot,
  tracks_serial = excluded.tracks_serial,
  tracks_expiry = excluded.tracks_expiry,
  max_stock = excluded.max_stock,
  reorder_point = excluded.reorder_point,
  part_number = excluded.part_number,
  manufacturer = excluded.manufacturer,
  subcategory = excluded.subcategory;

alter table public.inventory_items enable trigger inventory_items_protect_quantity;
commit;
